### 계좌 개설 API
POST http://localhost:8080/api/accounts
Content-Type: application/json

{
  "holderName": "janny"
}

> {%
client.test("Status", function() {
  client.assert(response.status, 200, "상태코드 200 확인");
});
%}

### 계좌 조회 API
GET http://localhost:8080/api/accounts/1

> {%
    client.test("Status", function() {
        client.assert(response.status, 200, "상태코드 200 확인");
    });
%}

### 계좌 해지 API
DELETE http://localhost:8080/api/accounts/1

> {%
    client.test("Status", function() {
        client.assert(response.status, 200, "상태코드 200 확인");
    });
%}